#!/usr/bin/python3
"""
GadgetSetAnalyzer (GSA)
This static analysis tool compares an original binary with one or more variants derived from it to determine how a
software transformation or difference in binary production (e.g., compiler used, optimizations selected) impacts the
set of code-reuse gadgets available. Several metrics are generated by GSA, and are described in the README.

Dependencies:
GSA uses the common tool <ROPgadget> under the hood to obtain a gadget catalog. Output of sensitive addresses uses the
<angr> library.

"""

# Standard Library Imports
import argparse
import sys
from datetime import datetime
import os

# Local Imports
from static_analyzer.GadgetSet import GadgetSet
from static_analyzer.GadgetStats import GadgetStats
from static_analyzer.AArch64 import ArmGadgetSet

LINE_SEP= "\n" # line separator

def format(x: float | int, difference: bool = False) -> str:
    if not difference:
        if isinstance(x, float):
            return f"{x:.3f}"
        else:
            return str(x)

    sign = "+" if x > 0 else ""

    if isinstance(x, float):
        return f"({sign}{x:.3f})"
    else:
        return f"({sign}{x})"

def create_output_directory(prefix, timestamp=True):
    if timestamp:
        directory_name = prefix + str(datetime.now())
    else:
        directory_name = prefix
    os.makedirs(directory_name)
    return directory_name

# Parse Arguments
parser = argparse.ArgumentParser()
parser.add_argument("original", help="Original program binary or directory of binaries.", type=str)
parser.add_argument("--variants", 
                    metavar="VARIANT=PATH",
                    nargs='+',
                    help="Sequence of variant names and variant paths.  Example: <variant_name1>=<file_path1> <variant_name1>=<file_path1>' ",
                    type=str)
parser.add_argument("--result_folder_name", help="Optionally specifies a specific output file name for the results folder.", action="store", type=str)
parser.add_argument("--original_name", help="Optionally specifies a specific name for the 'original' binary.", action="store", type=str, default="Original")
parser.add_argument("--architecture", type=str, default="x86-64", help="The architecture to analyze (x86-64 or aarch64)")
args = parser.parse_args()

variants_dict = {}
for variant in args.variants:
    parts = variant.split("=")
    if len(parts) != 2 or not parts[0] or not parts[1]:
        print("Error: variants are not in proper format")
        exit(1)
    variants_dict[parts[0]] = parts[1]

# Validate the target architecture.
architecture = args.architecture.lower()

if architecture not in ["x86-64", "aarch64"]:
    parser.error(f"unknown architecture '{architecture}' is neither 'x86-64' nor 'aarch64'")

print("Starting Gadget Set Analyzer")
# Create Gadget sets for original
print("Analyzing original package [" + args.original_name + "] located at: " + args.original)

if architecture == "x86-64":
    original = GadgetSet(args.original_name, args.original)
else:
    original = ArmGadgetSet(args.original_name, args.original)

try:
    if args.result_folder_name is None:
        directory_name = create_output_directory("results/analyzer_results_")
    else:
        directory_name = create_output_directory("results/" + args.result_folder_name, False)
except OSError as osErr:
    print("An OS Error occurred during creation of results directory: " + osErr.strerror)
    sys.exit("Results cannot be logged, aborting operation...")
print("Writing metrics files to " + directory_name)

rate_format = "{:.1%}"
float_format = "{:.2f}"

# Output File 7: Average Gadget Quality (and count of quality functional gadgets)
file_7_lines = ["Variant,# of ROP Gadgets,Avg ROP Quality,# of JOP Gadgets,Avg JOP Quality,# of COP Gadgets,Avg COP Quality,ROPgadget Chain?" + LINE_SEP]
orig_quality = f"{original.name},{format(len(original.ROPGadgets))},{format(original.averageROPQuality)},"
orig_quality += f"{format(len(original.JOPGadgets))},{format(original.averageJOPQuality)},"
orig_quality += f"{format(len(original.COPGadgets))},{format(original.averageCOPQuality)},{original.conatinsRopchain}" + LINE_SEP
file_7_lines.append(orig_quality)

# Iterate through the variants. Scan them to get a gadget set, compare it to the original, add data to output files
for key in variants_dict.keys():
    filepath = variants_dict.get(key)
    print("Analyzing variant package [" + key + "] located at: " + filepath)

    if architecture == "x86-64":
        variant = GadgetSet(key, filepath)
    else:
        variant = ArmGadgetSet(key, filepath)

    stat = GadgetStats(original, variant)

    # Output file 7 variant lines
    stat_quality = f"{variant.name},{format(len(variant.ROPGadgets))} {format(stat.keptQualityROPCountDiff, difference=True)},"
    stat_quality += f"{format(variant.averageROPQuality)} {format(stat.averageROPQualityDiff, difference=True)},"
    stat_quality += f"{format(len(variant.JOPGadgets))} {format(stat.keptQualityJOPCountDiff, difference=True)},"
    stat_quality += f"{format(variant.averageJOPQuality)} {format(stat.averageJOPQualityDiff, difference=True)},"
    stat_quality += f"{format(len(variant.COPGadgets))} {format(stat.keptQualityCOPCountDiff, difference=True)},"
    stat_quality += f"{format(variant.averageCOPQuality)} {format(stat.averageCOPQualityDiff, difference=True)},{variant.conatinsRopchain}{LINE_SEP}"
    file_7_lines.append(stat_quality)

# Write file lines to disk.
try:
    # Output file 7
    file = open(directory_name + "/Gadget Quality.csv", "w")
    file.writelines(file_7_lines)
    file.close()

except OSError as osErr:
    print(osErr)
