#!/usr/bin/python3
"""
GadgetSetAnalyzer (GSA)
This static analysis tool compares an original binary with one or more variants derived from it to determine how a
software transformation or difference in binary production (e.g., compiler used, optimizations selected) impacts the
set of code-reuse gadgets available. Several metrics are generated by GSA, and are described in the README.

Dependencies:
GSA uses the common tool <ROPgadget> under the hood to obtain a gadget catalog. Output of sensitive addresses uses the
<angr> library.

"""

# Standard Library Imports
import argparse
import sys

# Local Imports
from utility import *
from static_analyzer.GadgetSet import GadgetSet
from static_analyzer.GadgetStats import GadgetStats

LINE_SEP= "\n" # line separator

def format(x: float | int, difference: bool = False) -> str:
    if not difference:
        if isinstance(x, float):
            return f"{x:.3f}"
        else:
            return str(x)

    sign = "+" if x > 0 else ""

    if isinstance(x, float):
        return f"({sign}{x:.3f})"
    else:
        return f"({sign}{x})"

# Parse Arguments
parser = argparse.ArgumentParser()
parser.add_argument("original", help="Original program binary or directory of binaries.", type=str)
parser.add_argument("--variants", 
                    metavar="VARIANT=PATH",
                    nargs='+',
                    help="Sequence of variant names and variant paths.  Example: <variant_name1>=<file_path1> <variant_name1>=<file_path1>' ",
                    type=str)
parser.add_argument("--result_folder_name", help="Optionally specifies a specific output file name for the results folder.", action="store", type=str)
parser.add_argument("--original_name", help="Optionally specifies a specific name for the 'original' binary.", action="store", type=str, default="Original")
args = parser.parse_args()

variants_dict = {}
for variant in args.variants:
    parts = variant.split("=")
    if len(parts) != 2 or not parts[0] or not parts[1]:
        print("Error: variants are not in proper format")
        exit(1)
    variants_dict[parts[0]] = parts[1]

print("Starting Gadget Set Analyzer")

# Create Gadget sets for original
print("Analyzing original package [" + args.original_name + "] located at: " + args.original)
original = GadgetSet(args.original_name, args.original, False, False)

try:
    if args.result_folder_name is None:
        directory_name = create_output_directory("results/analyzer_results_")
    else:
        directory_name = create_output_directory("results/" + args.result_folder_name, False)
except OSError as osErr:
    print("An OS Error occurred during creation of results directory: " + osErr.strerror)
    sys.exit("Results cannot be logged, aborting operation...")
print("Writing metrics files to " + directory_name)

rate_format = "{:.1%}"
float_format = "{:.2f}"

# Output File 7: Average Gadget Quality (and count of quality functional gadgets)
file_7_lines = ["Variant,Number of Quality ROP Gadgets,Average ROP Gadget Quality,Number of Quality JOP Gadgets,Average JOP Gadget Quality,Number of Quality COP Gadgets,Average COP Gadget Quality" + LINE_SEP]
orig_quality = f"{original.name},{format(len(original.ROPGadgets))},{format(original.averageROPQuality)},"
orig_quality += f"{format(len(original.JOPGadgets))},{format(original.averageJOPQuality)},"
orig_quality += f"{format(len(original.COPGadgets))},{format(original.averageCOPQuality)}" + LINE_SEP
file_7_lines.append(orig_quality)

# Iterate through the variants. Scan them to get a gadget set, compare it to the original, add data to output files
for key in variants_dict.keys():
    filepath = variants_dict.get(key)
    print("Analyzing variant package [" + key + "] located at: " + filepath)

    variant = GadgetSet(key, filepath, False, False)
    stat = GadgetStats(original, variant, False, False)

    # Output file 7 variant lines
    stat_quality = f"{variant.name},{format(len(variant.ROPGadgets))} {format(stat.keptQualityROPCountDiff, difference=True)},"
    stat_quality += f"{format(variant.averageROPQuality)} {format(stat.averageROPQualityDiff, difference=True)},"
    stat_quality += f"{format(len(variant.JOPGadgets))} {format(stat.keptQualityJOPCountDiff, difference=True)},"
    stat_quality += f"{format(variant.averageJOPQuality)} {format(stat.averageJOPQualityDiff, difference=True)},"
    stat_quality += f"{format(len(variant.COPGadgets))} {format(stat.keptQualityCOPCountDiff, difference=True)},"
    stat_quality += f"{format(variant.averageCOPQuality)} {format(stat.averageCOPQualityDiff, difference=True)}{LINE_SEP}"
    file_7_lines.append(stat_quality)

# Write file lines to disk.
try:
    # Output file 7
    file = open(directory_name + "/Gadget Quality.csv", "w")
    file.writelines(file_7_lines)
    file.close()

except OSError as osErr:
    print(osErr)
